components:
  terraform:
    app:
      metadata:
        component: ecs-task
      vars:
        name: app
        ecs: !terraform.state ecs/cluster .
        vpc: !terraform.state vpc .
        lb: !terraform.state ecs/cluster .alb.public
        base_domains: !terraform.state ecs/cluster .records
        containers:
          app:
            image: !env APP_IMAGE 068007702576.dkr.ecr.us-east-2.amazonaws.com/cloudposse-examples/app-on-ecs-v2:sha-2ee4206
            memory: 256
            portMappings:
              - containerPort: 8080
            healthCheck:
              command: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
              interval: 30
              retries: 3
              startPeriod: 0
              timeout: 5
            mountPoints:
              - sourceVolume: test
                containerPath: /test
                readOnly: false
            logConfiguration:
                logDriver: "awslogs"
                options:
                    awslogs-create-group: true
                    awslogs-group: "app"
                    awslogs-region: "us-east-2"
                    awslogs-stream-prefix: "app"
          nginx: !include ../../components/ecs-task/sidecars/nginx.json
        task:
          volumes:
            test:
              host_path: /tmp
