components:
  terraform:
    app:
      metadata:
        component: ecs-task
      vars:
        name: app
        containers:
          app:
            image: 068007702576.dkr.ecr.us-east-2.amazonaws.com/cloudposse-examples/app-on-ecs-v2:sha-785867b
            memory: 256
            port_mappings:
              - containerPort: 80
            healthcheck:
              command: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
              interval: 30
              retries: 3
              startPeriod: 0
              timeout: 5
