import:
  - _default.yaml
  - defaults/app.yaml
  - deps/*

vars:
  stage: prod
  deps_stage: dev

terraform:
  auth:
    identities:
      plat-dev/admin:
        default: true
  
components:
  terraform:
    app:
      metadata:
        # Override Terraform workspace
        terraform_workspace: "{{ .vars.github_repo_name }}-{{ .atmos_stack }}-{{ .atmos_component }}"
